version: "3.2"
services:
    sql-server-db:
        container_name: "sql-server-db-local"
        image: "mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04"
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "I8well4sure"
            ACCEPT_EULA: "Y"
    mock-server:        
        container_name: "local-mock-server"
        image: "mockserver/mockserver"
        ports:
            - "1080:1080"    
    jaeger:
        container_name: "jaeger-local"
        image: "jaegertracing/all-in-one"
        ports:
            - "5775:5775/udp"
            - "6831:6831/udp"
            - "6832:6832/udp"
            - "5778:5778"
            - "16686:16686"
            - "14268:14268"
            - "14250:14250"
            - "9411:9411"
        environment:
            COLLECTOR_ZIPKIN_HTTP_PORT: "9411"